<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConferenceBooking.Bll\ConferenceBooking.Bll.csproj" />
    <ProjectReference Include="..\ConferenceBooking.Bll.Common\ConferenceBooking.Bll.Common.csproj" />
    <ProjectReference Include="..\ConferenceBooking.Dal.SqlRepositories\ConferenceBooking.Dal.SqlRepositories.csproj" />
  </ItemGroup>

</Project>
